[package]
name = "rust-kiss3d-game-template"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = {version = "1"}
futures-util = "0.3"
futures-channel = "0.3"
kiss3d = { version = "0.45.1", features = ["egui"]}
console_error_panic_hook = "0.1.7"
url = "2.5.8"
toml = "1.1.2"
rapier2d = "0.34.0"
hecs = "0.11.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
time = "0.3.47"
rodio = "0.22.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "0.3"
gloo-net = "0.7.0"
gloo-timers = { version = "0.4.0", features = ["futures"] }
time = { version = "0.3.47", features = ["wasm-bindgen"] }
rodio = { version = "0.22.2", features = ["wasm-bindgen"]}
